### ISSUE TITLE
How to download the model manually?

### ISSUE THREAD

**Issue by sunnyyangyangyang** [DenOfEquity/Hunyuan-DiT-for-webUI#1]
How to download the model manually instead of let the extension download it for me?

**Comment by DenOfEquity** [comment]
As far as this extension is concerned, it's a little complicated because I avoid downloading multiple copies of the text encoders and VAE. The diffusers type repositories, that this extension uses, are:
```
https://huggingface.co/Tencent-Hunyuan/HunyuanDiT-Diffusers
https://huggingface.co/Tencent-Hunyuan/HunyuanDiT-Diffusers-Distilled
https://huggingface.co/Tencent-Hunyuan/HunyuanDiT-v1.1-Diffusers
https://huggingface.co/Tencent-Hunyuan/HunyuanDiT-v1.1-Diffusers-Distilled
```
The first repo is used for everything, the others use only the ```transformer``` subfolder. For example: If you intend to use only v1.1 distilled, you would need the transformer from that model; everything from the first repo except its transformer; and nothing from the other repos.

I haven't tested this, and will not: You could manually download all repository contents, preserving directory structure, into ```{webui directory}/models/diffusers/{repo}``` where local repo names are of the form ```models--Tencent-Hunyuan--HunyuanDiT-Diffusers```, inserting ```-v1.1``` and ```-Distilled``` as appropriate.

Or you could use [huggingface-cli](https://huggingface.co/docs/huggingface_hub/guides/cli).
